name: vision
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-cuda
  - opencv
  - pillow
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip